export const authenticationService = 'http://34.76.205.89/usercontroller/api/Users/login'
export const availablestockService = 'http://34.76.205.89/availablestocksbroker/api/AvailableStocks'
export const buyerService = 'http://34.76.205.89/stocksharerequester/api/StockShareRequester/'
export const sellerService = 'http://34.76.205.89/stockshareprovider/api/StockShareProvicer/'
export const myStocksService = 'http://34.76.205.89/userstocksbroker/api/UserStocksBroker/'
export const usersService = 'http://34.76.205.89/usercontroller/api/Users/'