export const authenticationService = 'http://itonkgr14tseis.dk/usercontroller/api/Users/login'
export const availablestockService = 'http://itonkgr14tseis.dk/availablestocksbroker/api/AvailableStocks'
export const buyerService = 'http://itonkgr14tseis.dk/stocksharerequester/api/StockShareRequester/'
export const sellerService = 'http://itonkgr14tseis.dk/stockshareprovider/api/StockShareProvicer/'
export const myStocksService = 'http://itonkgr14tseis.dk/userstocksbroker/api/UserStocksBroker/'
export const usersService = 'http://itonkgr14tseis.dk/usercontroller/api/Users/'