// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserController.Data;

namespace UserController.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200521152819_usermigcontext")]
    partial class usermigcontext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UserController.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "flow@mail.dk",
                            Name = "flow",
                            Password = "1234"
                        },
                        new
                        {
                            Id = 2,
                            Email = "ras@mail.dk",
                            Name = "ras",
                            Password = "1234"
                        },
                        new
                        {
                            Id = 3,
                            Email = "thom@mail.dk",
                            Name = "thom",
                            Password = "1234"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
